channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - flask=2.1.0
  - sqlalchemy=1.4.22
  - psycopg2  # (PostgreSQL 사용 시 필요)
  - flask-bcrypt=0.7.1
  - flask-socketio=5.1.0
  - eventlet
  - pip
  - pip:
      - flask_migrate==3.1.0
      - flask_sqlalchemy==2.5.1
      - flask_wtf==1.0.0
      - flask-login==0.5.0
      - flask-bcrypt==0.7.1
      - flask-session==0.3.2
      - flask-socketio==5.1.0
      - flask-mail==0.9.1
      - werkzeug==2.0.3  # 추가
      - email-validator  # 이메일 검증을 위한 패키지 추가
      - python-dotenv
