"""Final fix for migration

Revision ID: 026d4ced3bfe
Revises: 94bd55ff427f
Create Date: 2025-04-24 20:32:06.380691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026d4ced3bfe'
down_revision = '94bd55ff427f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_post_buyer_id', 'user', ['buyer_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Integer(), nullable=True))
        batch_op.drop_column('wallet_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_balance', sa.FLOAT(), nullable=True))
        batch_op.drop_column('balance')

    with op.batch_alter_table('post', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        pass
    # ### end Alembic commands ###
