"""Add buyer and is_sold to Post

Revision ID: 2262068c09ea
Revises: 846f36b20b72
Create Date: 2025-04-24 20:12:45.596821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2262068c09ea'
down_revision = '846f36b20b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('buyer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['buyer_id'], ['id'])
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=True))
    op.drop_column('user', 'wallet_balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_balance', sa.FLOAT(), nullable=True))
    op.drop_column('user', 'balance')
    #op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'buyer_id')
    # ### end Alembic commands ###
