"""Fix migration status

Revision ID: 94bd55ff427f
Revises: 2262068c09ea
Create Date: 2025-04-24 20:22:31.758248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bd55ff427f'
down_revision = '2262068c09ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['buyer_id'], ['id'])
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=True))
    op.drop_column('user', 'wallet_balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wallet_balance', sa.FLOAT(), nullable=True))
    op.drop_column('user', 'balance')
    #op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
